### ISSUE TITLE
Running Catalog Lightcurve Time and Data Set Time Don't Match

### ISSUE THREAD

**Issue by ycendes** [transientskp/banana#111]
I noticed that when checking light curves like this one- http://banana.transientskp.org/master/vlo_SB003cendes/runningcatalog/5503/ the time on the lightcurve versus the first data points is off by one hour, where the light curve is one hour behind the time stamps in the data file. (I should note that even if the light curve was trying to convert to local time this would be incorrect, as we are one hour ahead of UTC.)  Dit is slecht!

**Comment by gijzelaerr** [comment]
ok so when I look at this page:

http://banana.transientskp.org/master/vlo_SB003cendes/image/80314/

```
Filename: F5.73257e+07_S1-63_T20-11-2013_16-57-00.image
start date (UT): Nov. 20, 2013, 5:57 p.m.
```

I think since LOFAR/AARTFAAC is in NL it specifies the time in the filename as Central European Time. But  since AARTFAAC doesn't specify a timezone TraP assumes it actually is UCT, and stores it this way. Since our banana server is in NL it assumes dutch time zone and will add one hour to the display. So the problem is  in the AARTFAAC naming of files. Bouncing this to @Error323 , please reopen this issue if my analysis is wrong.

**Comment by ajstewart** [comment]
I'm getting the same issue in Australia using VLA data. The time listed by the TraP is the correct start time, the highcharts plot is behind by one hour.

<img width="394" alt="highcharts" src="https://user-images.githubusercontent.com/3306161/41515123-e014b040-72ef-11e8-9cc8-2aed01289208.png">
<img width="202" alt="trap" src="https://user-images.githubusercontent.com/3306161/41515127-e5414ad8-72ef-11e8-9868-c762942bb0c5.png">
