### ISSUE TITLE
Navigation buttons on image page 

### ISSUE THREAD

**Issue by hsuyeep** [transientskp/banana#93]
Clicking on the 'images' button of a TraP run gives details of all images in the run as a table. Clicking on an image id gives a page with more details on that image. However, there is no way to move between images, other than going back to the tabular display. There is a navigation button above and below the table of extracted sources, but that doesn't work for AARTFAAC runs

**Comment by timstaley** [comment]
Hey Peeyush, there should be (at least in Banana R2) a 'next image (by time)' button, is that not there?

**Comment by hsuyeep** [comment]
![image](https://cloud.githubusercontent.com/assets/1520321/9232074/e430bdc0-412b-11e5-8212-3e9f794347a6.png)
Hi Tim, I see the navigation buttons next to the '1' above the source parameter table in the attachment, are those the ones you're talking about?  I cannot click them... Gijs mentioned in today's meeting that it was problematic in AARTFAAC images, but I can't recall why.

**Comment by gijzelaerr** [comment]
the problem is related to the skyregion problem. 

The actual query is here:

https://github.com/transientskp/banana/blob/master/banana/models.py#L269

where you can see that the queryset is also filtered on the matching skyregion. That doesn't work since every image has its own skyregion. We can probably solve that by removing that skyregion, but first I want to make sure what the implications would be. @timstaley what do you think?

**Comment by gijzelaerr** [comment]
@hsuyeep  I've modified this, banana master will restart in couple of minutes, please verify if this works as required.

**Comment by gijzelaerr** [comment]
@hsuyeep please reopen this issue if this does not work.

**Comment by hsuyeep** [comment]
This works now. Thanks!
